// <auto-generated />
using ControllerOfficeStudentResultSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControllerOfficeStudentResultSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201020142240_StringConvert")]
    partial class StringConvert
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControllerOfficeStudentResultSystem.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ExcelPath");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new { ID = 1, Program = "BSc", SubjectName = "Software_Engineering", Year = "2020" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
